name: "CI"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Get the required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libudev-dev llvm libclang-dev protobuf-compiler libssl-dev
        shell: bash

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.88.0

      - name: Cache Solana installation
        uses: actions/cache@v4
        id: cache-solana
        with:
          path: ~/.local/share/solana
          key: solana-${{ runner.os }}-v2.1.16

      - name: Install Solana CLI v2.1.16
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.16/install)"

      - name: Add Solana to PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache Anchor installation
        uses: actions/cache@v4
        id: cache-anchor
        with:
          path: |
            ~/.avm
            ~/.cargo/bin/avm
          key: anchor-${{ runner.os }}-0.31.1

      - name: Install avm and Anchor CLI
        if: steps.cache-anchor.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --force
          avm install 0.31.1
        shell: bash

      - name: Use Anchor CLI version
        run: |
          avm use 0.31.1
          echo "$HOME/.avm/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build the programs via Anchor
        run: anchor build
        shell: bash

      - name: Log tool versions
        run: |
          echo "rustc: $(rustc --version)"
          echo "solana: $(solana --version)"
          echo "anchor: $(anchor --version)"
