name: Test Solana Program

# Run this workflow on pushes and pull requests to any branch
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79.0
          target: wasm32-unknown-unknown
          override: true

      - name: Install dependencies
        run: yarn install

      - name: Install Solana CLI
        run: |
          wget -qO- "https://release.anza.xyz/v1.17.25/solana-release-x86_64-unknown-linux-gnu.tar.bz2" | tar -xvj
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        shell: bash

      - name: Install Anchor CLI
        run: npm install -g @coral-xyz/anchor-cli@v0.29.0
        shell: bash

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Anchor Test
        run: yarn run test
        shell: bash
